# Generated by Django 5.2.9 on 2026-01-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="court_size",
            field=models.CharField(default="Standard", max_length=50),
        ),
        migrations.AddField(
            model_name="venue",
            name="facilities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="venue_images/"),
        ),
        migrations.AddField(
            model_name="venue",
            name="sport_type",
            field=models.CharField(
                choices=[("FUTSAL", "Futsal"), ("BADMINTON", "Badminton")],
                default="FUTSAL",
                max_length=10,
            ),
        ),
    ]
