# Generated by Django 5.2.9 on 2026-01-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0003_venueavailability"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuebooking",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="venuebooking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
