# Generated by Django 6.0 on 2026-01-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0004_venuebooking_amount_venuebooking_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuebooking",
            name="purpose",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
