# Generated by Django 6.0 on 2026-01-26 08:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0005_venuebooking_purpose"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="venueavailability",
            options={"ordering": ["date"]},
        ),
        migrations.RenameField(
            model_name="venueavailability",
            old_name="end_time",
            new_name="closing_time",
        ),
        migrations.RenameField(
            model_name="venueavailability",
            old_name="start_time",
            new_name="opening_time",
        ),
        migrations.AlterUniqueTogether(
            name="venueavailability",
            unique_together={("venue", "date")},
        ),
        migrations.AddField(
            model_name="venue",
            name="advance_booking_days",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="venue",
            name="default_closing_time",
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AddField(
            model_name="venue",
            name="default_opening_time",
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
        migrations.AddField(
            model_name="venue",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="operating_days",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="venue",
            name="slot_duration_minutes",
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name="venueavailability",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="VenueTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_available", models.BooleanField(default=True)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
                "unique_together": {("venue", "date", "start_time", "end_time")},
            },
        ),
    ]
