# Generated by Django 6.0 on 2026-01-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0006_alter_venueavailability_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="advance_booking_days",
        ),
        migrations.RemoveField(
            model_name="venue",
            name="slot_duration_minutes",
        ),
        migrations.DeleteModel(
            name="VenueTimeSlot",
        ),
    ]
