# Generated by Django 6.0 on 2026-01-26 09:11

from django.db import migrations, models
from datetime import time


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0007_remove_venue_advance_booking_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='default_opening_time',
            field=models.TimeField(default=time(6, 0)),
        ),
        migrations.AddField(
            model_name='venue',
            name='default_closing_time',
            field=models.TimeField(default=time(22, 0)),
        ),
        migrations.AddField(
            model_name='venue',
            name='operating_days',
            field=models.JSONField(default=list),
        ),
    ]
