# Generated by Django 6.0 on 2026-03-05 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0009_add_approval_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VenueAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("APPROVE", "Approve Venue"),
                            ("REJECT", "Reject Venue"),
                            ("CONDITIONAL_APPROVE", "Conditional Approval"),
                            ("BULK_APPROVE", "Bulk Approve Venues"),
                            ("BULK_REJECT", "Bulk Reject Venues"),
                            ("VIEW_DOCUMENT", "View Verification Document"),
                            ("REQUEST_DOCUMENTS", "Request Additional Documents"),
                        ],
                        db_index=True,
                        max_length=25,
                    ),
                ),
                (
                    "venue_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="For bulk operations, list of affected venue IDs",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True, help_text="Status before this action", max_length=25
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, help_text="Status after this action", max_length=25
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason provided for rejection or conditional approval",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (IP address, user agent, validation results)",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RenameIndex(
            model_name="venue",
            new_name="venues_venu_approva_bd577f_idx",
            old_name="venues_approval_id_idx",
        ),
        migrations.RenameIndex(
            model_name="venue",
            new_name="venues_venu_sport_t_250b2f_idx",
            old_name="venues_sport_approval_idx",
        ),
        migrations.RenameIndex(
            model_name="venue",
            new_name="venues_venu_owner_i_d00d90_idx",
            old_name="venues_owner_approval_idx",
        ),
        migrations.AddField(
            model_name="venueauditlog",
            name="administrator",
            field=models.ForeignKey(
                limit_choices_to={"role": "ADMIN"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="venue_admin_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="venueauditlog",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_logs",
                to="venues.venue",
            ),
        ),
        migrations.AddIndex(
            model_name="venueauditlog",
            index=models.Index(
                fields=["administrator", "timestamp"],
                name="venues_venu_adminis_f308b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="venueauditlog",
            index=models.Index(
                fields=["action_type", "timestamp"],
                name="venues_venu_action__aa2b5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="venueauditlog",
            index=models.Index(
                fields=["venue", "timestamp"], name="venues_venu_venue_i_02eee8_idx"
            ),
        ),
    ]
