# Generated by Django 6.0 on 2026-03-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0014_venue_multi_sport_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuebooking",
            name="payment_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Payment deadline; booking auto-expires after this time",
                null=True,
            ),
        ),
    ]
