# Generated by Django 5.2.9 on 2025-12-24 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tournaments", "0001_initial"),
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizerNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("REGISTRATION_UPDATE", "Registration Update"),
                            ("PAYMENT_RECEIVED", "Payment Received"),
                            ("TOURNAMENT_REMINDER", "Tournament Reminder"),
                            ("VENUE_CONFIRMATION", "Venue Confirmation"),
                            ("REFEREE_REQUEST", "Referee Request"),
                            ("SYSTEM_ANNOUNCEMENT", "System Announcement"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("read", models.BooleanField(default=False)),
                ("action_url", models.URLField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("related_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizer_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "venue_booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="venues.venuebooking",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(blank=True, max_length=200)),
                (
                    "business_license",
                    models.FileField(blank=True, null=True, upload_to="licenses/"),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("social_media_links", models.JSONField(blank=True, default=dict)),
                ("years_experience", models.IntegerField(default=0)),
                ("specializations", models.JSONField(blank=True, default=list)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizerSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("BASIC", "Basic"),
                            ("PREMIUM", "Premium"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        default="FREE",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("max_tournaments_per_month", models.IntegerField(default=5)),
                ("max_participants_per_tournament", models.IntegerField(default=32)),
                ("advanced_analytics", models.BooleanField(default=False)),
                ("priority_support", models.BooleanField(default=False)),
                ("custom_branding", models.BooleanField(default=False)),
                (
                    "organizer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("sport_type", models.CharField(max_length=50)),
                (
                    "tournament_type",
                    models.CharField(
                        choices=[
                            ("SINGLE_ELIMINATION", "Single Elimination"),
                            ("DOUBLE_ELIMINATION", "Double Elimination"),
                            ("ROUND_ROBIN", "Round Robin"),
                            ("SWISS", "Swiss System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("default_max_participants", models.IntegerField(default=16)),
                (
                    "default_entry_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("default_rules", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_registrations", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("views_count", models.IntegerField(default=0)),
                ("completion_rate", models.FloatField(default=0.0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("feedback_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "unique_together": {("organizer", "tournament")},
            },
        ),
    ]
