# Generated by Django 5.2.9 on 2026-01-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournamenttemplate",
            name="organizer",
        ),
        migrations.DeleteModel(
            name="TournamentAnalytics",
        ),
        migrations.DeleteModel(
            name="TournamentTemplate",
        ),
    ]
