# Generated by Django 6.0 on 2026-01-19 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0002_remove_tournamenttemplate_organizer_and_more"),
        ("tournaments", "0004_remove_tournamenttemplate_organizer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("sport_type", models.CharField(max_length=50)),
                (
                    "tournament_type",
                    models.CharField(
                        choices=[
                            ("SINGLE_ELIMINATION", "Single Elimination"),
                            ("DOUBLE_ELIMINATION", "Double Elimination"),
                            ("ROUND_ROBIN", "Round Robin"),
                            ("SWISS", "Swiss System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("default_max_participants", models.IntegerField(default=16)),
                (
                    "default_entry_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("default_rules", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_registrations", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("views_count", models.IntegerField(default=0)),
                ("completion_rate", models.FloatField(default=0.0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("feedback_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "unique_together": {("organizer", "tournament")},
            },
        ),
    ]
