# Generated by Django 6.0 on 2026-01-07 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
        ("venues", "0005_venuebooking_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="linked_venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments",
                to="venues.venue",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="venue_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournament",
                to="venues.venuebooking",
            ),
        ),
    ]
