# Generated by Django 5.2.9 on 2026-01-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0003_tournamenttemplate_tournamentanalytics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournamenttemplate",
            name="organizer",
        ),
        migrations.DeleteModel(
            name="TournamentAnalytics",
        ),
        migrations.DeleteModel(
            name="TournamentTemplate",
        ),
    ]
