# Generated by Django 6.0 on 2026-01-26 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        ("tournaments", "0004_remove_tournamenttemplate_organizer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="team1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_team1",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_team2",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="winning_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_matches",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="allow_substitutes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tournament",
            name="max_substitutes",
            field=models.IntegerField(
                default=0, help_text="Maximum number of substitute players allowed"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="registration_type",
            field=models.CharField(
                choices=[("INDIVIDUAL", "Individual"), ("TEAM", "Team")],
                default="INDIVIDUAL",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="team_size",
            field=models.IntegerField(
                default=1, help_text="Required number of players per team"
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="sport_type",
            field=models.CharField(
                choices=[("FUTSAL", "Futsal"), ("BADMINTON", "Badminton")],
                max_length=50,
            ),
        ),
    ]
