# Generated by Django 6.0 on 2026-02-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0006_remove_tournament_formats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="tournament_type",
            field=models.CharField(
                choices=[
                    ("SINGLE_ELIMINATION", "Single Elimination"),
                    ("knockout", "Knockout"),
                    ("league", "League"),
                ],
                db_index=True,
                default="knockout",
                max_length=20,
            ),
        ),
    ]
