# Generated by Django 6.0 on 2026-02-03 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_enhance_futsal_detailed_scoring"),
        ("tournaments", "0007_add_league_tournament_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["tournament", "round_number"],
                name="tournaments_tournam_99ac32_idx",
            ),
        ),
    ]
