# Generated by Django 6.0 on 2026-02-03 01:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0008_add_match_round_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerMatchStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("goals", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_statistics",
                        to="tournaments.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        limit_choices_to={"role": "PLAYER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_statistics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Match Statistics",
                "verbose_name_plural": "Player Match Statistics",
                "indexes": [
                    models.Index(
                        fields=["player", "match"],
                        name="tournaments_player__137442_idx",
                    ),
                    models.Index(
                        fields=["match"], name="tournaments_match_i_95fdf5_idx"
                    ),
                    models.Index(fields=["goals"], name="tournaments_goals_e382ea_idx"),
                    models.Index(
                        fields=["assists"], name="tournaments_assists_b2afe2_idx"
                    ),
                ],
                "unique_together": {("player", "match")},
            },
        ),
    ]
