# Generated by Django 6.0 on 2026-02-20 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("tournaments", "0009_add_player_match_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentregistration",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournament_registrations",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="tournamentregistration",
            name="payment_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tournamentregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_PAYMENT", "Pending Payment"),
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("WITHDRAWN", "Withdrawn"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
