# Generated by Django 6.0 on 2026-03-05 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0011_add_approval_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("APPROVE", "Approve Tournament"),
                            ("REJECT", "Reject Tournament"),
                            ("CONDITIONAL_APPROVE", "Conditional Approval"),
                            ("BULK_APPROVE", "Bulk Approve Tournaments"),
                            ("BULK_REJECT", "Bulk Reject Tournaments"),
                            ("VIEW_DOCUMENT", "View Verification Document"),
                            ("REQUEST_DOCUMENTS", "Request Additional Documents"),
                        ],
                        db_index=True,
                        max_length=25,
                    ),
                ),
                (
                    "tournament_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="For bulk operations, list of affected tournament IDs",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True, help_text="Status before this action", max_length=25
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, help_text="Status after this action", max_length=25
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason provided for rejection or conditional approval",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (IP address, user agent, validation results)",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RenameIndex(
            model_name="tournament",
            new_name="tournaments_approva_d18c50_idx",
            old_name="tournaments_approval_created_idx",
        ),
        migrations.RenameIndex(
            model_name="tournament",
            new_name="tournaments_sport_t_c87f1c_idx",
            old_name="tournaments_sport_approval_idx",
        ),
        migrations.RenameIndex(
            model_name="tournament",
            new_name="tournaments_organiz_89b30d_idx",
            old_name="tournaments_organizer_approval_idx",
        ),
        migrations.RenameIndex(
            model_name="tournament",
            new_name="tournaments_date_cb062c_idx",
            old_name="tournaments_date_approval_idx",
        ),
        migrations.AddField(
            model_name="tournamentauditlog",
            name="administrator",
            field=models.ForeignKey(
                limit_choices_to={"role": "ADMIN"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tournament_admin_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournamentauditlog",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_logs",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentauditlog",
            index=models.Index(
                fields=["administrator", "timestamp"],
                name="tournaments_adminis_725a61_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentauditlog",
            index=models.Index(
                fields=["action_type", "timestamp"],
                name="tournaments_action__5c580c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentauditlog",
            index=models.Index(
                fields=["tournament", "timestamp"],
                name="tournaments_tournam_d57774_idx",
            ),
        ),
    ]
