# Generated by Django 6.0 on 2026-03-14 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0012_tournamentauditlog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentRefereeAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("CONFIRMED", "Confirmed"),
                            ("DECLINED", "Declined"),
                            ("CANCELLED", "Cancelled"),
                            ("CONVERTED", "Converted to Match Bookings"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Agreed referee fee for the tournament",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "referee",
                    models.ForeignKey(
                        limit_choices_to={"role": "REFEREE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_availability",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "ORGANIZER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referee_availability_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referee_availability",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Referee Availability",
                "verbose_name_plural": "Tournament Referee Availabilities",
            },
        ),
        migrations.DeleteModel(
            name="RefereeBooking",
        ),
        migrations.AddIndex(
            model_name="tournamentrefereeavailability",
            index=models.Index(
                fields=["tournament", "status"], name="tournaments_tournam_34d487_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentrefereeavailability",
            index=models.Index(
                fields=["referee", "status"], name="tournaments_referee_81feae_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentrefereeavailability",
            unique_together={("tournament", "referee")},
        ),
    ]
