# Generated by Django 6.0 on 2026-03-17 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tournaments",
            "0013_tournamentrefereeavailability_delete_refereebooking_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentauditlog",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="tournaments.tournament",
            ),
        ),
    ]
