# Generated by Django 6.0 on 2026-03-27 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_teamtournamentregistration_payment_and_more"),
        ("tournaments", "0014_fix_audit_log_tournament_on_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchRemark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "remark_type",
                    models.CharField(
                        choices=[
                            ("PENALTY", "Penalty"),
                            ("YELLOW_CARD", "Yellow Card"),
                            ("RED_CARD", "Red Card"),
                            ("FOUL", "Foul"),
                            ("INJURY", "Injury"),
                            ("SUBSTITUTION", "Substitution"),
                            ("DISPUTE", "Dispute"),
                            ("CUSTOM", "Custom Note"),
                        ],
                        default="CUSTOM",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                (
                    "player_name",
                    models.CharField(
                        blank=True,
                        help_text="Player name (free text for flexibility)",
                        max_length=200,
                    ),
                ),
                (
                    "minute",
                    models.IntegerField(
                        blank=True,
                        help_text="Match minute when this occurred",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Short summary", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "ORGANIZER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_remarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remarks",
                        to="tournaments.match",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_remarks",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["minute", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["match", "remark_type"],
                        name="tournaments_match_i_3e97e8_idx",
                    ),
                    models.Index(
                        fields=["match", "created_at"],
                        name="tournaments_match_i_415a27_idx",
                    ),
                ],
            },
        ),
    ]
