# Generated by Django 6.0 on 2026-03-15 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("referees", "0003_remove_duplicate_availabilities"),
        (
            "tournaments",
            "0013_tournamentrefereeavailability_delete_refereebooking_and_more",
        ),
        ("venues", "0014_venue_multi_sport_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="referee_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_records",
                to="referees.refereebooking",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="tournaments.tournament",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="venue_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="venues.venuebooking",
            ),
        ),
    ]
