# Generated by Django 5.2.9 on 2025-12-22 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_reset_tokens_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="playerjoinrequest",
            name="from_player",
            field=models.ForeignKey(
                limit_choices_to={"role": "PLAYER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="playerjoinrequest",
            name="to_player",
            field=models.ForeignKey(
                limit_choices_to={"role": "PLAYER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="playerstatistics",
            name="player",
            field=models.ForeignKey(
                limit_choices_to={"role": "PLAYER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_stats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="upcomingmatch",
            name="player",
            field=models.ForeignKey(
                limit_choices_to={"role": "PLAYER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upcoming_matches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="upcomingmatch",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tournaments.tournament",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playerstatistics",
            unique_together={("player", "year", "month")},
        ),
    ]
