# Generated by Django 5.2.9 on 2025-12-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("PLAYER", "Player"),
                    ("ORGANIZER", "Organizer"),
                    ("REFEREE", "Referee"),
                    ("VENUE_OWNER", "Venue Owner"),
                ],
                default="PLAYER",
                max_length=20,
            ),
        ),
    ]
