# Generated by Django 6.0 on 2026-01-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_blacklistedtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="business_contact",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="business_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customuser",
            name="business_registration",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
