# Generated by Django 6.0 on 2026-02-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_customuser_business_contact_customuser_business_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="wallet_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
