# Generated by Django 6.0 on 2026-02-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_wallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("REGISTRATION_CONFIRMED", "Registration Confirmed"),
                    ("REGISTRATION_REJECTED", "Registration Rejected"),
                    ("TOURNAMENT_UPDATED", "Tournament Updated"),
                    ("MATCH_SCHEDULED", "Match Scheduled"),
                    ("BOOKING_CONFIRMED", "Booking Confirmed"),
                    ("PAYMENT_RECEIVED", "Payment Received"),
                    ("NEW_MESSAGE", "New Message"),
                    ("NEW_GROUP_MESSAGE", "New Group Message"),
                    ("GENERAL", "General Notification"),
                ],
                default="GENERAL",
                max_length=30,
            ),
        ),
    ]
