# Generated by Django 6.0 on 2026-03-03 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_notification_notification_type"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("APPROVE", "Approve User"),
                            ("REJECT", "Reject User"),
                            ("BULK_APPROVE", "Bulk Approve Users"),
                            ("BULK_REJECT", "Bulk Reject Users"),
                            ("VIEW_DOCUMENT", "View Verification Document"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "target_user_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="For bulk operations, list of affected user IDs",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason provided for rejection actions"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (IP address, user agent, etc.)",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AddField(
            model_name="customuser",
            name="approval_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the account was approved or rejected",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Current approval status of the user account",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Administrator who approved or rejected this account",
                limit_choices_to={"role": "ADMIN"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Explanation provided when account is rejected"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="verification_document",
            field=models.FileField(
                blank=True,
                help_text="Identity or business registration document",
                max_length=500,
                null=True,
                upload_to="verification_documents/%Y/%m/",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["approval_status", "created_at"],
                name="accounts_cu_approva_5abdfe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["role", "approval_status"], name="accounts_cu_role_5f8514_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="accounts_cu_email_5ce40b_idx"),
        ),
        migrations.AddField(
            model_name="adminauditlog",
            name="administrator",
            field=models.ForeignKey(
                limit_choices_to={"role": "ADMIN"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admin_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adminauditlog",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="adminauditlog",
            index=models.Index(
                fields=["administrator", "timestamp"],
                name="accounts_ad_adminis_45d94e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adminauditlog",
            index=models.Index(
                fields=["action_type", "timestamp"],
                name="accounts_ad_action__092df7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adminauditlog",
            index=models.Index(
                fields=["target_user", "timestamp"],
                name="accounts_ad_target__153efe_idx",
            ),
        ),
    ]
