# Generated by Django 6.0 on 2026-01-26 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tournaments", "0004_remove_tournamenttemplate_organizer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("sport_types", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("max_size", models.IntegerField(default=15)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        limit_choices_to={"role": "PLAYER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "player",
                    models.ForeignKey(
                        limit_choices_to={"role": "PLAYER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        limit_choices_to={"role": "PLAYER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_team_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="teams.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FutsalScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("goals", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="futsal_scores",
                        to="tournaments.match",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="futsal_scores",
                        to="teams.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("TEAM_CREATED", "Team Created"),
                            ("MEMBER_ADDED", "Member Added"),
                            ("MEMBER_REMOVED", "Member Removed"),
                            ("ROLE_CHANGED", "Role Changed"),
                            ("TOURNAMENT_REGISTERED", "Tournament Registered"),
                            ("MATCH_PLAYED", "Match Played"),
                            ("OWNERSHIP_TRANSFERRED", "Ownership Transferred"),
                            ("INVITATION_SENT", "Invitation Sent"),
                            ("INVITATION_ACCEPTED", "Invitation Accepted"),
                            ("INVITATION_DECLINED", "Invitation Declined"),
                        ],
                        max_length=25,
                    ),
                ),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_history",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("LEADER", "Leader"),
                            ("MEMBER", "Member"),
                        ],
                        default="MEMBER",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "player",
                    models.ForeignKey(
                        limit_choices_to={"role": "PLAYER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="teams.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamTournamentRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "PLAYER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_tournament_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "selected_players",
                    models.ManyToManyField(
                        limit_choices_to={"role": "PLAYER"},
                        related_name="selected_for_tournaments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_registrations",
                        to="teams.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_registrations",
                        to="tournaments.tournament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BadmintonSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("set_number", models.IntegerField()),
                ("home_score", models.IntegerField()),
                ("away_score", models.IntegerField()),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badminton_sets",
                        to="tournaments.match",
                    ),
                ),
            ],
            options={
                "ordering": ["set_number"],
                "unique_together": {("match", "set_number")},
            },
        ),
        migrations.CreateModel(
            name="FutsalPlayerStat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("goals", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("minutes_played", models.IntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        limit_choices_to={"role": "PLAYER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="futsal_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "futsal_score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="teams.futsalscore",
                    ),
                ),
            ],
            options={
                "unique_together": {("futsal_score", "player")},
            },
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["name"], name="teams_team_name_43e047_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["owner"], name="teams_team_owner_i_7dde75_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["is_active"], name="teams_team_is_acti_6dafc6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("name",),
                name="unique_active_team_name",
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["player", "status"], name="teams_invit_player__29ac0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["team", "status"], name="teams_invit_team_id_baf1cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["expires_at"], name="teams_invit_expires_65bb35_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invitation",
            unique_together={("team", "player")},
        ),
        migrations.AlterUniqueTogether(
            name="futsalscore",
            unique_together={("match", "team")},
        ),
        migrations.AddIndex(
            model_name="activityhistory",
            index=models.Index(
                fields=["team", "-timestamp"], name="teams_activ_team_id_ffab74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activityhistory",
            index=models.Index(
                fields=["event_type", "-timestamp"],
                name="teams_activ_event_t_2de957_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(
                fields=["team", "role"], name="teams_teamm_team_id_4d95f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(
                fields=["player", "is_active"], name="teams_teamm_player__eb2e13_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teammembership",
            unique_together={("team", "player")},
        ),
        migrations.AddIndex(
            model_name="teamtournamentregistration",
            index=models.Index(
                fields=["tournament", "status"], name="teams_teamt_tournam_be707b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamtournamentregistration",
            index=models.Index(
                fields=["team", "status"], name="teams_teamt_team_id_7ba43d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teamtournamentregistration",
            unique_together={("tournament", "team")},
        ),
    ]
