# Generated by Django 6.0 on 2026-01-30 04:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="futsalplayerstat",
            name="clearances",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="futsalplayerstat",
            name="fouls_committed",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="futsalplayerstat",
            name="fouls_suffered",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="futsalplayerstat",
            name="interceptions",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="futsalplayerstat",
            name="is_starter",
            field=models.BooleanField(
                default=True, help_text="Whether player started the match"
            ),
        ),
        migrations.AddField(
            model_name="futsalplayerstat",
            name="passes_attempted",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="futsalplayerstat",
            name="passes_completed",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="futsalplayerstat",
            name="red_cards",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="futsalplayerstat",
            name="shots_off_target",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="futsalplayerstat",
            name="shots_on_target",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="futsalplayerstat",
            name="tackles",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="futsalplayerstat",
            name="yellow_cards",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="futsalscore",
            name="fouls",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="futsalscore",
            name="possession_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="futsalscore",
            name="red_cards",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="futsalscore",
            name="shots_off_target",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="futsalscore",
            name="shots_on_target",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="futsalscore",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="futsalscore",
            name="yellow_cards",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name="FutsalCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[("YELLOW", "Yellow Card"), ("RED", "Red Card")],
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("UNSPORTING_BEHAVIOR", "Unsporting Behavior"),
                            ("DISSENT", "Dissent by Word or Action"),
                            ("PERSISTENT_FOULING", "Persistent Fouling"),
                            ("DELAYING_GAME", "Delaying the Restart of Play"),
                            (
                                "FAILING_DISTANCE",
                                "Failing to Respect Required Distance",
                            ),
                            (
                                "ENTERING_LEAVING",
                                "Entering or Leaving Field Without Permission",
                            ),
                            ("SERIOUS_FOUL", "Serious Foul Play"),
                            ("VIOLENT_CONDUCT", "Violent Conduct"),
                            ("OFFENSIVE_LANGUAGE", "Offensive Language/Gestures"),
                            ("SECOND_YELLOW", "Second Yellow Card"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "minute",
                    models.IntegerField(help_text="Minute when card was issued"),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "futsal_score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="teams.futsalscore",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="futsal_cards_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["minute"],
            },
        ),
        migrations.CreateModel(
            name="FutsalGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "minute",
                    models.IntegerField(help_text="Minute when goal was scored"),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular Goal"),
                            ("PENALTY", "Penalty"),
                            ("FREE_KICK", "Free Kick"),
                            ("OWN_GOAL", "Own Goal"),
                        ],
                        default="REGULAR",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the goal"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assist_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="futsal_assists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "futsal_score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_details",
                        to="teams.futsalscore",
                    ),
                ),
                (
                    "scorer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="futsal_goals_scored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["minute"],
            },
        ),
    ]
