# Generated by Django 6.0 on 2026-02-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_enhance_futsal_detailed_scoring"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="max_size",
            field=models.IntegerField(default=50),
        ),
    ]
