# Generated by Django 6.0 on 2026-02-03 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_change_max_size_to_50"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityhistory",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("TEAM_CREATED", "Team Created"),
                    ("MEMBER_ADDED", "Member Added"),
                    ("MEMBER_REMOVED", "Member Removed"),
                    ("ROLE_CHANGED", "Role Changed"),
                    ("TOURNAMENT_REGISTERED", "Tournament Registered"),
                    ("MATCH_PLAYED", "Match Played"),
                    ("OWNERSHIP_TRANSFERRED", "Ownership Transferred"),
                    ("INVITATION_SENT", "Invitation Sent"),
                    ("INVITATION_ACCEPTED", "Invitation Accepted"),
                    ("INVITATION_DECLINED", "Invitation Declined"),
                    ("JOIN_REQUEST_SENT", "Join Request Sent"),
                    ("JOIN_REQUEST_ACCEPTED", "Join Request Accepted"),
                    ("JOIN_REQUEST_DECLINED", "Join Request Declined"),
                ],
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="TeamJoinRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Optional message from player"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        limit_choices_to={"role": "PLAYER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "PLAYER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_join_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["player", "status"],
                        name="teams_teamj_player__296fd7_idx",
                    ),
                    models.Index(
                        fields=["team", "status"], name="teams_teamj_team_id_c0168d_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="teams_teamj_created_d1bdb4_idx"
                    ),
                ],
                "unique_together": {("team", "player")},
            },
        ),
    ]
