# Generated by Django 6.0 on 2026-02-20 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("teams", "0004_alter_activityhistory_event_type_teamjoinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamtournamentregistration",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_tournament_registrations",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="teamtournamentregistration",
            name="payment_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teamtournamentregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_PAYMENT", "Pending Payment"),
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
