# Generated by Django 6.0 on 2026-04-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_teamtournamentregistration_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("LEADER", "Leader"),
                    ("CAPTAIN", "Captain"),
                    ("MEMBER", "Member"),
                ],
                default="MEMBER",
                max_length=10,
            ),
        ),
    ]
