# Generated by Django 6.0 on 2026-02-25 06:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_conversationmetadata_messageattachment_userpresence_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("DIRECT", "Direct Message"),
                            ("TEAM", "Team Chat"),
                            ("TOURNAMENT", "Tournament Channel"),
                        ],
                        default="DIRECT",
                        max_length=20,
                    ),
                ),
                ("associated_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "chat_rooms",
            },
        ),
        migrations.CreateModel(
            name="ChatRoomParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "chat_room_participants",
            },
        ),
        migrations.AlterField(
            model_name="conversationmetadata",
            name="other_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_metadata_reverse",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages_chat",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conversationmetadata",
            unique_together={("user", "other_user")},
        ),
        migrations.AddField(
            model_name="conversationmetadata",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata",
                to="chat.chatroom",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chatroom",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conversationmetadata",
            unique_together={("user", "other_user"), ("user", "room")},
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["room", "-timestamp"], name="chat_msg_room_ts_idx"
            ),
        ),
        migrations.AddField(
            model_name="chatroomparticipant",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="chat.chatroom",
            ),
        ),
        migrations.AddField(
            model_name="chatroomparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatroomparticipant",
            unique_together={("room", "user")},
        ),
    ]
