# Generated by Django 6.0 on 2026-02-25 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatroom_chatroomparticipant_and_more"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create GroupChat model
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='group_chat',
                    to='teams.team'
                )),
            ],
            options={
                'db_table': 'chat_group_chats',
            },
        ),
        
        # Create GroupMessage model
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('content', models.TextField()),
                ('message_type', models.CharField(
                    max_length=10,
                    choices=[
                        ('TEXT', 'Text'),
                        ('IMAGE', 'Image'),
                        ('VIDEO', 'Video'),
                        ('AUDIO', 'Audio'),
                        ('DOCUMENT', 'Document'),
                    ],
                    default='TEXT'
                )),
                ('status', models.CharField(
                    max_length=10,
                    choices=[
                        ('SENT', 'Sent'),
                        ('DELIVERED', 'Delivered'),
                        ('FAILED', 'Failed'),
                    ],
                    default='SENT'
                )),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(null=True, blank=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True, blank=True)),
                ('group_chat', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='messages',
                    to='chat.groupchat'
                )),
                ('sender', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='sent_group_messages',
                    to=settings.AUTH_USER_MODEL
                )),
                ('reply_to', models.ForeignKey(
                    on_delete=django.db.models.deletion.SET_NULL,
                    null=True,
                    blank=True,
                    related_name='replies',
                    to='chat.groupmessage'
                )),
            ],
            options={
                'db_table': 'chat_group_messages',
                'ordering': ['timestamp'],
            },
        ),
        
        # Create GroupMessageReadReceipt model
        migrations.CreateModel(
            name='GroupMessageReadReceipt',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='read_receipts',
                    to='chat.groupmessage'
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='group_message_receipts',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'db_table': 'chat_group_message_read_receipts',
            },
        ),
        
        # Create RefereeOrganizerRelationship model
        migrations.CreateModel(
            name='RefereeOrganizerRelationship',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referee', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='organizer_relationships',
                    limit_choices_to={'role': 'REFEREE'},
                    to=settings.AUTH_USER_MODEL
                )),
                ('organizer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='referee_relationships',
                    limit_choices_to={'role': 'ORGANIZER'},
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'db_table': 'chat_referee_organizer_relationships',
            },
        ),
        
        # Add indexes for GroupChat
        migrations.AddIndex(
            model_name='groupchat',
            index=models.Index(fields=['team'], name='chat_grp_team_idx'),
        ),
        
        # Add indexes for GroupMessage
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['group_chat', '-timestamp'], name='chat_grp_msg_chat_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['sender', '-timestamp'], name='chat_grp_msg_sender_ts_idx'),
        ),
        
        # Add unique constraint and index for GroupMessageReadReceipt
        migrations.AlterUniqueTogether(
            name='groupmessagereadreceipt',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='groupmessagereadreceipt',
            index=models.Index(fields=['message', 'user'], name='chat_grp_rcpt_msg_usr_idx'),
        ),
        
        # Add unique constraint and indexes for RefereeOrganizerRelationship
        migrations.AlterUniqueTogether(
            name='refereeorganizerrelationship',
            unique_together={('referee', 'organizer')},
        ),
        migrations.AddIndex(
            model_name='refereeorganizerrelationship',
            index=models.Index(fields=['referee', 'organizer'], name='chat_ref_org_idx'),
        ),
        migrations.AddIndex(
            model_name='refereeorganizerrelationship',
            index=models.Index(fields=['organizer', 'referee'], name='chat_org_ref_idx'),
        ),
    ]
