# Generated by Django 6.0 on 2026-02-25 10:45

from django.db import migrations


def populate_referee_relationships(apps, schema_editor):
    """Create relationships from existing RefereeBooking records"""
    RefereeBooking = apps.get_model('referees', 'RefereeBooking')
    RefereeOrganizerRelationship = apps.get_model('chat', 'RefereeOrganizerRelationship')
    
    # Get all unique referee-organizer pairs from bookings
    bookings = RefereeBooking.objects.values('referee', 'requested_by').distinct()
    
    relationships = []
    for booking in bookings:
        relationships.append(
            RefereeOrganizerRelationship(
                referee_id=booking['referee'],
                organizer_id=booking['requested_by']
            )
        )
    
    # Bulk create relationships, ignoring conflicts (if relationship already exists)
    RefereeOrganizerRelationship.objects.bulk_create(
        relationships,
        ignore_conflicts=True
    )


def reverse_populate(apps, schema_editor):
    """Reverse migration - delete all relationships"""
    RefereeOrganizerRelationship = apps.get_model('chat', 'RefereeOrganizerRelationship')
    RefereeOrganizerRelationship.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_add_group_chat_models"),
        ("referees", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_referee_relationships, reverse_populate),
    ]
