# Generated by Django 6.0 on 2026-02-25 10:46

from django.db import migrations


def create_group_chats_for_teams(apps, schema_editor):
    """Create GroupChat for all existing active teams"""
    Team = apps.get_model('teams', 'Team')
    GroupChat = apps.get_model('chat', 'GroupChat')
    
    # Get all active teams
    teams = Team.objects.filter(is_active=True)
    
    group_chats = []
    for team in teams:
        group_chats.append(GroupChat(team=team))
    
    # Bulk create group chats, ignoring conflicts (if group chat already exists)
    GroupChat.objects.bulk_create(group_chats, ignore_conflicts=True)


def reverse_create(apps, schema_editor):
    """Reverse migration - delete all group chats"""
    GroupChat = apps.get_model('chat', 'GroupChat')
    GroupChat.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_populate_referee_relationships"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_group_chats_for_teams, reverse_create),
    ]
