# Generated by Django 6.0 on 2026-02-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_create_team_group_chats"),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmetadata',
            name='conversation_type',
            field=models.CharField(
                max_length=10,
                choices=[('DIRECT', 'Direct'), ('GROUP', 'Group')],
                default='DIRECT'
            ),
        ),
    ]
