# Generated by Django 5.2.9 on 2025-12-24 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefereeCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certification_name", models.CharField(max_length=200)),
                ("issuing_body", models.CharField(max_length=200)),
                ("certification_number", models.CharField(max_length=100, unique=True)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "certificate_file",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "referee",
                    models.ForeignKey(
                        limit_choices_to={"role": "REFEREE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefereeMatchReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_duration", models.DurationField(blank=True, null=True)),
                ("weather_conditions", models.CharField(blank=True, max_length=100)),
                ("court_conditions", models.CharField(blank=True, max_length=100)),
                ("incidents", models.TextField(blank=True)),
                ("penalties_issued", models.TextField(blank=True)),
                ("notable_events", models.TextField(blank=True)),
                ("overall_assessment", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referee_report",
                        to="tournaments.match",
                    ),
                ),
                (
                    "referee",
                    models.ForeignKey(
                        limit_choices_to={"role": "REFEREE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_reports",
                        to="tournaments.tournament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefereeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certification_level",
                    models.CharField(
                        choices=[
                            ("LEVEL_1", "Level 1 - Beginner"),
                            ("LEVEL_2", "Level 2 - Intermediate"),
                            ("LEVEL_3", "Level 3 - Advanced"),
                            ("LEVEL_4", "Level 4 - Professional"),
                            ("INTERNATIONAL", "International"),
                        ],
                        default="LEVEL_1",
                        max_length=50,
                    ),
                ),
                ("sports_specialization", models.JSONField(blank=True, default=list)),
                ("years_experience", models.IntegerField(default=0)),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("license_expiry", models.DateField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                ("rating", models.FloatField(default=0.0)),
                ("total_matches_officiated", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefereeAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "referee",
                    models.ForeignKey(
                        limit_choices_to={"role": "REFEREE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referee_availabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["available_date", "start_time"],
                "unique_together": {("referee", "available_date")},
            },
        ),
        migrations.CreateModel(
            name="RefereeBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REQUESTED",
                        max_length=10,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("match_date", models.DateTimeField()),
                ("fee", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("notes", models.TextField(blank=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referee_bookings_referees",
                        to="tournaments.match",
                    ),
                ),
                (
                    "referee",
                    models.ForeignKey(
                        limit_choices_to={"role": "REFEREE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referee_bookings_referees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "ORGANIZER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referee_requests_referees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referee_bookings_referees",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ["match_date"],
                "unique_together": {("referee", "match")},
            },
        ),
        migrations.CreateModel(
            name="RefereeRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referee_ratings",
                        to="tournaments.match",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        limit_choices_to={"role": "ORGANIZER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referee",
                    models.ForeignKey(
                        limit_choices_to={"role": "REFEREE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referee_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referee_ratings",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "unique_together": {("referee", "organizer", "match")},
            },
        ),
    ]
