# Generated by Django 6.0 on 2026-01-19 05:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="refereeavailability",
            unique_together={("referee", "available_date", "start_time", "end_time")},
        ),
    ]
