# Generated by Django 6.0 on 2026-03-15 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_referee_booking_and_more"),
        ("referees", "0003_remove_duplicate_availabilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="refereebooking",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referee_bookings",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="refereebooking",
            name="payment_released",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="refereebooking",
            name="payment_released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="refereebooking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("RELEASED", "Released"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
