# Generated by Django 6.0 on 2026-01-19 06:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referees", "0003_remove_duplicate_availabilities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="refereeavailability",
            unique_together={("referee", "available_date")},
        ),
    ]
