# Generated by Django 6.0 on 2026-03-15 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referees", "0004_refereebooking_payment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefereeGeneralAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekly_pattern", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "referee",
                    models.OneToOneField(
                        limit_choices_to={"role": "REFEREE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="general_availability",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
