# Generated by Django 6.0 on 2026-03-15 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referees", "0005_refereegeneralavailability"),
        (
            "tournaments",
            "0013_tournamentrefereeavailability_delete_refereebooking_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="refereebooking",
            unique_together={("referee", "tournament")},
        ),
        migrations.AlterField(
            model_name="refereebooking",
            name="match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referee_bookings_referees",
                to="tournaments.match",
            ),
        ),
    ]
