# Generated by Django 6.0 on 2026-03-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referees", "0009_referee_payment_tracking_model"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="refereepaymentrecord",
            new_name="referees_re_referee_44fdfa_idx",
            old_name="referees_re_referee_c8e8a5_idx",
        ),
        migrations.RenameIndex(
            model_name="refereepaymentrecord",
            new_name="referees_re_tournam_96d7bb_idx",
            old_name="referees_re_tournam_8f9a2c_idx",
        ),
        migrations.AlterField(
            model_name="refereeprofile",
            name="sports_specialization",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
